### ISSUE TITLE
Show Private Images

### ISSUE THREAD

**Issue by petems** [boats/barge#12]
Currently there's no way to get users private images:

https://developers.digitalocean.com/documentation/v2/#list-a-user-s-images

Example Call:

```
curl -X GET -H 'Content-Type: application/json' -H 'Authorization: Bearer b7d03a6947b217efb6f3ec3bd3504582' "https://api.digitalocean.com/v2/images?page=1&per_page=1&private=true"
```

**Comment by blom** [comment]
I think `barge.image.all(private: true)` should work?

**Comment by petems** [comment]
@blom Cool, I'll try that out, and if it works add a spec for it :+1:
